print("Name: Sumit Ramani")
print("Roll No: 24BEE124")
names_set = set()
names_set.update({"Hello", "Hi", "Bye","Haha" ,"Lol"})
print("After adding names:", names_set)
names_set.discard("Bye") 
names_set.add("hey")  
print("After modifying a name:", names_set)
names_set.discard("Hello")
names_set.discard("Hi")
print("After deleting two names:", names_set)
